

####


GET http://localhost:3000/candidate

####

POST http://localhost:3000/candidate
content-type: application/json

{
    "candidate" : {
        "dni": 1,
        "partido": "erfwcasdcas",
        "presidente": "",
        "vicepresidente": ""
    }
}

####

DELETE http://localhost:3000/candidate/5d98ced9131e67392cf42101

####

DELETE http://localhost:3000/candidate