

####
GET http://localhost:3000/voter

####

POST http://localhost:3000/voter
content-type: application/json

{
    "voter" : {
        "dni": 12341234,
        "name": "",
        "lastname": "",
        "email": "",
        "password": "qwe"
    }
}

####
DELETE http://localhost:3000/voter/5d9dd20a6ff3b82b036b4d92

####
DELETE http://localhost:3000/voter