####
GET http://localhost:3000/voter

####
POST http://localhost:3000/vote
content-type: application/json

{
    "voter" : {
        "id": "5d9e586578f7031306de2480"
    },
    "candidate" : {
        "id" : "5d9e54f4b25f677e2e2f37c8"
    }
}